### ISSUE TITLE
mountsshfs FileNotFoundError

### ISSUE THREAD

**Issue by PascalinDe** [mfherbst/mfhBin#1]
When running mountsshfs.sh from $HOME for the first time, the following error message is shown (**replaced by me**). Manually creating an empty directory .mfhBin fixed the problem and a default configuration file will be created when running the script again.

Cheers!

Dropping default config at: **$HOME**.mfhBin/mountsshfs.yaml
Traceback (most recent call last):
  File "./mfhBin/mountsshfs", line 752, in <module>
    cfg = get_config(argdict["config_path"])
  File "./mfhBin/mountsshfs", line 728, in get_config
    with open(default_config_path,"w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '**$HOME**.mfhBin/mountsshfs.yaml'

**Comment by mfherbst** [comment]
Fixed in  9792abb. Thanks.
